import { Inter } from "next/font/google"
import "./styles/global-style.scss"
import FirebseAuthContext from "./components/contextes/FirebseAuthContext.jsx"
import LogicContext from "./components/contextes/LogicContext.jsx"
import CartFav from "./components/CartFav"
import FirebaseFirestoreContext from "./components/contextes/FirebaseFirestoreContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <FirebaseFirestoreContext>
          <LogicContext>
            <FirebseAuthContext>
              {/* <Navbar></Navbar> */}
              {/* This is rendering twice so make sure to fix */}
              {children}
              <CartFav />
            </FirebseAuthContext>
          </LogicContext>
        </FirebaseFirestoreContext>
      </body>
    </html>
  )
}
